// Sample listings for local development when Supabase is not running

export const sampleListings = [
  {
    id: "sample-001",
    listing_title_anonymous: "Established SaaS Platform for Enterprise Clients",
    anonymous_business_description: "A profitable B2B SaaS company providing workflow automation tools to enterprise clients across Southeast Asia. Strong recurring revenue base with 95% annual retention rate and growing customer pipeline.",
    asking_price: 3500000,
    industry: "Information Technology (IT)",
    location_country: "Singapore",
    location_city_region_general: "Central Region",
    year_established: 2017,
    number_of_employees: "11-25",
    business_website_url: "https://example-saas.com",
    image_urls: [],
    status: "active",
    is_seller_verified: true,
    listing_verification_status: "verified",
    created_at: "2025-11-15T08:00:00Z",
    updated_at: "2025-12-01T10:00:00Z",
    seller_id: "sample-seller-001",
    annual_revenue_range: "$1M - $5M USD",
    net_profit_margin_range: "30% - 40%",
    specific_annual_revenue_last_year: 2800000,
    specific_net_profit_last_year: 950000,
    adjusted_cash_flow: 1050000,
    ebitda: 1100000,
    key_strength_1: "95% annual customer retention rate",
    key_strength_2: "Proprietary AI-powered automation engine",
    key_strength_3: "Long-term enterprise contracts with blue-chip clients",
    growth_opportunity_1: "Expansion into Japanese and Korean markets",
    growth_opportunity_2: "Launch of premium analytics module",
    growth_opportunity_3: "Strategic partnerships with regional system integrators",
    key_strengths_anonymous: ["95% annual customer retention rate", "Proprietary AI-powered automation engine", "Long-term enterprise contracts with blue-chip clients"],
    specific_growth_opportunities: "• Expansion into Japanese and Korean markets\n• Launch of premium analytics module\n• Strategic partnerships with regional system integrators",
    business_model: "SaaS subscription with annual enterprise contracts",
    deal_structure_looking_for: ["Share Purchase", "Earn-out Agreement"],
    reason_for_selling_anonymous: "Founder pursuing a new venture in a different sector",
    detailed_reason_for_selling: "The founder has been building this company for 8 years and is ready to move on to a new challenge in climate tech.",
    social_media_links: "LinkedIn: linkedin.com/company/example-saas",
    registered_business_name: "TechFlow Solutions Pte Ltd",
  },
  {
    id: "sample-002",
    listing_title_anonymous: "Premium F&B Chain with 6 Locations",
    anonymous_business_description: "A well-known restaurant and café chain operating 6 locations across Kuala Lumpur. Known for fusion cuisine combining Southeast Asian and Western flavors. Strong brand recognition and loyal customer base with active social media following.",
    asking_price: 1800000,
    industry: "Food & Beverage",
    location_country: "Malaysia",
    location_city_region_general: "Kuala Lumpur",
    year_established: 2015,
    number_of_employees: "51-100",
    business_website_url: "https://example-restaurant.com",
    image_urls: [],
    status: "active",
    is_seller_verified: true,
    listing_verification_status: "verified",
    created_at: "2025-10-20T06:00:00Z",
    updated_at: "2025-11-15T09:00:00Z",
    seller_id: "sample-seller-002",
    annual_revenue_range: "$1M - $5M USD",
    net_profit_margin_range: "20% - 30%",
    specific_annual_revenue_last_year: 3200000,
    specific_net_profit_last_year: 720000,
    adjusted_cash_flow: 810000,
    ebitda: 850000,
    key_strength_1: "6 prime locations in high-traffic areas",
    key_strength_2: "Strong brand with 50K+ social media followers",
    key_strength_3: "Proven operational systems and trained management team",
    growth_opportunity_1: "Franchise model expansion across Malaysia",
    growth_opportunity_2: "Cloud kitchen and delivery-only locations",
    growth_opportunity_3: "Packaged retail product line (sauces, meal kits)",
    key_strengths_anonymous: ["6 prime locations in high-traffic areas", "Strong brand with 50K+ social media followers", "Proven operational systems and trained management team"],
    specific_growth_opportunities: "• Franchise model expansion across Malaysia\n• Cloud kitchen and delivery-only locations\n• Packaged retail product line (sauces, meal kits)",
    business_model: "Multi-location restaurant chain with dine-in and delivery",
    deal_structure_looking_for: ["Asset Purchase", "Share Purchase"],
    reason_for_selling_anonymous: "Owner relocating internationally for family reasons",
    detailed_reason_for_selling: "The owner is relocating to Australia to be closer to family and cannot manage operations remotely.",
    social_media_links: "Instagram: @example-restaurant, Facebook: /example-restaurant",
    registered_business_name: "Golden Plate Holdings Sdn Bhd",
  },
  {
    id: "sample-003",
    listing_title_anonymous: "Logistics & Freight Forwarding Company",
    anonymous_business_description: "A full-service logistics provider specializing in cross-border freight forwarding between Indonesia, Singapore, and Malaysia. Established relationships with major shipping lines and a proprietary tracking platform used by over 200 active corporate clients.",
    asking_price: 5200000,
    industry: "Logistics & Supply Chain",
    location_country: "Indonesia",
    location_city_region_general: "Jakarta",
    year_established: 2012,
    number_of_employees: "26-50",
    business_website_url: "https://example-logistics.com",
    image_urls: [],
    status: "active",
    is_seller_verified: false,
    listing_verification_status: "unverified",
    created_at: "2025-12-01T04:00:00Z",
    updated_at: "2025-12-10T07:00:00Z",
    seller_id: "sample-seller-003",
    annual_revenue_range: "$5M - $10M USD",
    net_profit_margin_range: "10% - 20%",
    specific_annual_revenue_last_year: 7500000,
    specific_net_profit_last_year: 1125000,
    adjusted_cash_flow: 1300000,
    ebitda: 1450000,
    key_strength_1: "200+ active corporate clients with recurring contracts",
    key_strength_2: "Proprietary shipment tracking and management platform",
    key_strength_3: "Established relationships with 15+ major shipping lines",
    growth_opportunity_1: "Expansion into Vietnam and Thailand corridors",
    growth_opportunity_2: "Warehousing and fulfillment services",
    growth_opportunity_3: "E-commerce last-mile delivery partnership",
    key_strengths_anonymous: ["200+ active corporate clients with recurring contracts", "Proprietary shipment tracking and management platform", "Established relationships with 15+ major shipping lines"],
    specific_growth_opportunities: "• Expansion into Vietnam and Thailand corridors\n• Warehousing and fulfillment services\n• E-commerce last-mile delivery partnership",
    business_model: "B2B freight forwarding with long-term corporate contracts",
    deal_structure_looking_for: ["Share Purchase"],
    reason_for_selling_anonymous: "Strategic exit after successful growth phase",
    detailed_reason_for_selling: "The founders have built the company to a scale where institutional ownership would unlock the next level of growth.",
    social_media_links: "LinkedIn: linkedin.com/company/example-logistics",
    registered_business_name: "PT Indo Freight Solutions",
  },
  {
    id: "sample-004",
    listing_title_anonymous: "Digital Marketing Agency with Regional Clients",
    anonymous_business_description: "A boutique digital marketing agency serving mid-market and enterprise clients across ASEAN. Specializes in performance marketing, SEO, and content strategy with a strong track record of delivering measurable ROI for clients in fintech, e-commerce, and healthcare sectors.",
    asking_price: 950000,
    industry: "Marketing & Advertising",
    location_country: "Thailand",
    location_city_region_general: "Bangkok",
    year_established: 2019,
    number_of_employees: "11-25",
    business_website_url: "https://example-agency.com",
    image_urls: [],
    status: "active",
    is_seller_verified: true,
    listing_verification_status: "verified",
    created_at: "2025-12-05T03:00:00Z",
    updated_at: "2025-12-12T05:00:00Z",
    seller_id: "sample-seller-004",
    annual_revenue_range: "$500K - $1M USD",
    net_profit_margin_range: "30% - 40%",
    specific_annual_revenue_last_year: 820000,
    specific_net_profit_last_year: 295000,
    adjusted_cash_flow: 310000,
    ebitda: 320000,
    key_strength_1: "85% client retention rate with long-term retainers",
    key_strength_2: "Specialized expertise in fintech and healthcare verticals",
    key_strength_3: "Fully remote team with low overhead costs",
    growth_opportunity_1: "AI-powered content and analytics services",
    growth_opportunity_2: "Expansion into influencer marketing",
    growth_opportunity_3: "White-label services for larger agencies",
    key_strengths_anonymous: ["85% client retention rate with long-term retainers", "Specialized expertise in fintech and healthcare verticals", "Fully remote team with low overhead costs"],
    specific_growth_opportunities: "• AI-powered content and analytics services\n• Expansion into influencer marketing\n• White-label services for larger agencies",
    business_model: "Monthly retainer contracts with performance bonuses",
    deal_structure_looking_for: ["Asset Purchase", "Earn-out Agreement"],
    reason_for_selling_anonymous: "Founder pursuing full-time role at a tech company",
    detailed_reason_for_selling: "The founder received an offer to lead marketing at a major tech company and wants to ensure the agency continues thriving under new ownership.",
    social_media_links: "LinkedIn: linkedin.com/company/example-agency, Twitter: @example-agency",
    registered_business_name: "BrightPulse Digital Co., Ltd.",
  },
];

// Transform a raw sample listing to the API response format used by GET /api/listings
export function transformSampleForList(listing: typeof sampleListings[0]) {
  return {
    id: listing.id,
    title: listing.listing_title_anonymous,
    short_description: listing.anonymous_business_description,
    asking_price: listing.asking_price,
    industry: listing.industry,
    location_country: listing.location_country,
    location_city: listing.location_city_region_general,
    established_year: listing.year_established,
    number_of_employees: listing.number_of_employees,
    website_url: listing.business_website_url,
    images: listing.image_urls,
    status: listing.status,
    verification_status: listing.is_seller_verified ? 'verified' : 'pending',
    created_at: listing.created_at,
    updated_at: listing.updated_at,
    seller_id: listing.seller_id,
    annual_revenue_range: listing.annual_revenue_range,
    net_profit_margin_range: listing.net_profit_margin_range,
    verified_annual_revenue: listing.specific_annual_revenue_last_year,
    verified_net_profit: listing.specific_net_profit_last_year,
    verified_cash_flow: listing.adjusted_cash_flow,
    key_strength_1: listing.key_strength_1,
    key_strength_2: listing.key_strength_2,
    key_strength_3: listing.key_strength_3,
    growth_opportunity_1: listing.growth_opportunity_1,
    growth_opportunity_2: listing.growth_opportunity_2,
    growth_opportunity_3: listing.growth_opportunity_3,
    key_strengths_anonymous: listing.key_strengths_anonymous,
    specific_growth_opportunities: listing.specific_growth_opportunities,
  };
}

// Transform a raw sample listing to the API response format used by GET /api/listings/[id]
export function transformSampleForDetail(listing: typeof sampleListings[0]) {
  return {
    ...transformSampleForList(listing),
    business_model: listing.business_model,
    deal_structure_looking_for: listing.deal_structure_looking_for,
    reason_for_selling_anonymous: listing.reason_for_selling_anonymous,
    detailed_reason_for_selling: listing.detailed_reason_for_selling,
    adjusted_cash_flow: listing.adjusted_cash_flow,
    ebitda: listing.ebitda,
    social_media_links: listing.social_media_links,
    registered_business_name: listing.registered_business_name,
    is_seller_verified: listing.is_seller_verified,
    financial_documents_url: null,
    key_metrics_report_url: null,
    ownership_documents_url: null,
    financial_snapshot_url: null,
    ownership_details_url: null,
    location_real_estate_info_url: null,
    web_presence_info_url: null,
    secure_data_room_link: null,
  };
}
